name: Build several projects inside docker image

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build-projects:
    runs-on: ubuntu-latest
    container: ghcr.io/carlosperate/ubit-toolchain:latest
    steps:
      - name: Check Versions
        run: |
          arm-none-eabi-gcc --version
          cmake --version
          ninja --version
          srec_cat --version
      - name: Clone MicroPython
        run: git clone https://github.com/bbcmicrobit/micropython.git
      - name: Build MicroPython
        run: |
          cd micropython
          yt target bbc-microbit-classic-gcc-nosd
          yt up
          make all
      - name: Clone microbit-samples
        run: git clone https://github.com/lancaster-university/microbit-samples.git
      - name: Build DAL samples
        run: |
          cd microbit-samples
          yt target bbc-microbit-classic-gcc
          yt up
          yt build
