name: Deploy images with latest and versioned tags

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build base image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/ubit-toolchain:latest .
      - name: Tag same base image with the versioned tag
        run: docker tag ghcr.io/${{ github.repository_owner }}/ubit-toolchain:latest ghcr.io/${{ github.repository_owner }}/ubit-toolchain:${{ github.ref }}
      - name: Push base images to ghcr.io
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/ubit-toolchain:latest
          docker push ghcr.io/${{ github.repository_owner }}/ubit-toolchain:${{ github.ref }}

      - name: Build codespaces image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/devcontainer-ubit:latest .
      - name: Tag same codespaces image with the versioned tag
        run: docker tag ghcr.io/${{ github.repository_owner }}/devcontainer-ubit:latest ghcr.io/${{ github.repository_owner }}/devcontainer-ubit:${{ github.ref }}
      - name: Push codespaces images to ghcr.io
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/devcontainer-ubit:latest
          docker push ghcr.io/${{ github.repository_owner }}/devcontainer-ubit:${{ github.ref }}
