name: Deploy versioned & latest

on:
  release:
    types: [published]

jobs:
  deploy-base:
    name: Deploy base image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build base image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/microbit-toolchain:latest .
      - name: Tag same base image with the versioned tag
        run: docker tag ghcr.io/${{ github.repository_owner }}/microbit-toolchain:latest ghcr.io/${{ github.repository_owner }}/microbit-toolchain:${{ steps.get_version.outputs.VERSION }}
      - name: Push base images to ghcr.io
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/microbit-toolchain:${{ steps.get_version.outputs.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/microbit-toolchain:latest

  deploy-devcontainer:
    name: Deploy devcontainer
    needs: deploy-base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build codespaces image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/devcontainer-microbit:latest codespaces
      - name: Tag same codespaces image with the versioned tag
        run: docker tag ghcr.io/${{ github.repository_owner }}/devcontainer-microbit:latest ghcr.io/${{ github.repository_owner }}/devcontainer-microbit:${{ steps.get_version.outputs.VERSION }}
      - name: Push codespaces images to ghcr.io
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/devcontainer-microbit:${{ steps.get_version.outputs.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/devcontainer-microbit:latest
